
# version 1

# web:
#   build: .
#   ports:
#     - "5000:5000"
#   links:
#     - mongo
# mongo:
#   image: mongo:latest


# version 2

version: '2'
services:
  web:
    build: .
    image: web
    ports:
      - 5000:5000
  mongo:
    image: mongo:latest
